en_template_task = [
    # for
    "Could you provide instructions for '{}'?",
    "I'm wondering what the process is for '{}'.",
    "What's the proper procedure for '{}'?",
    "What are the recommended steps for '{}'?",
    "I'm inquiring about the procedure for '{}'.",
    "What are the essential steps for '{}'?",
    "Could you walk me through the steps for '{}'?",
    "What's the recommended course of action for '{}'?",
    "Could you offer some suggestions for '{}'?",
    "I'd like to know the steps to take for '{}'.",
    "What's the procedure for '{}'?",
    "I'm inquiring about the recommended steps for '{}'.",
    "What's your recommended approach for '{}'?",
    "Can you provide recommendations for '{}'?",
    "I'm curious about the steps required for '{}'.",
    "I need to know the necessary steps for '{}'.",
    "What's the most efficient method for '{}'?",
    "Could you provide a step-by-step guide for '{}'?",
    "I'd like some tips and tricks for '{}'.",
    "What's the preferred course of action for '{}'?",
    "Could you suggest some best practices for '{}'?",
    "What's the most effective strategy for '{}'?",
    # to
    "Can you advise me on how to {}?",
    "I'm looking for guidance on how to {}.",
    "What steps do I need to take to {}?",
    "I need assistance with planning to {}.",
    "I'd like to know the best way to {}.",
    "What's the most effective way to {}?",
    "Could you guide me through the steps to {}?",
    "What would be the best approach to {}?",
    "I'm seeking your advice on how to {}.",
    "I'm curious about the best way to {}.",
    "I'm not sure where to begin when it comes to {}.",
    "I'm wondering about the best approach to {}.",
    "I'd like to get some tips on how to {}.",
    "What are the key steps to {}?",
    "Can you shed light on the best way to {}?",
    "What would you recommend as the first step to {}?",
    "What's your advice for someone looking to {}?",
    "Could you show me the proper way to {}?",
    "I'm not sure how to start when it comes to {}.",
    "What's the proper way to {}?",
    "What's the best way to {}?",
    # of
    "I'm interested in the process of '{}'.",
    "Can you explain the process of '{}'?",
    "How can I make the most of '{}'?",
    "I'm interested in understanding the process of '{}'.",
    "I'm seeking your input on the process of '{}'.",
    # with
    "I'm unsure how to start with '{}'.",
    "I'm not sure where to begin with '{}'.",
    "How do I get started with '{}'?",
    "How should I proceed with '{}'?",
    "How can I ensure success with '{}'?",
    "I'm not sure where to start with '{}'.",
    "I'd like some guidance on where to start with '{}'.",
    "How can I achieve success with '{}'?",
    "How can I ensure a successful outcome with '{}'?",
    # on
    "I need some insights on '{}'.",
    "I'd appreciate your advice on '{}'.",
    "Can you shed light on '{}'?",
    "I'd like some guidance on '{}'.",
    "I'd like to get some advice on '{}'.",
    "I'm interested in your expertise on '{}'.",
    "I'd appreciate some advice on '{}'.",
    "I'm seeking your guidance on '{}'.",
    "Can you share your insights on '{}'?",
    "I'm looking for advice on '{}'.",
    "Could you provide some guidance on '{}'?",
    "I'm seeking your expertise on '{}'.",
    "I'd appreciate your guidance on '{}'.",
    "I'm interested in your insights on '{}'.",
    "I'm seeking your expert advice on '{}'.",
    # other
    "I'm seeking advice on accomplishing '{}'.",
    "Is there a strategy for successfully '{}'?",
    "Can you explain how to tackle '{}'?",
    "What steps are involved in '{}'?",
    "What steps should I follow to complete '{}'?",
    "Can you explain how to tackle '{}' step by step?",
    "Can you explain the steps involved in '{}'?",
    "I'd like to understand the necessary steps to complete '{}'.",
]
